<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('vendor/css/ext-theme-classic-all.css')) ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->appendFile($this->basePath('vendor/js/ext-all.js'))
        ->appendFile($this->basePath('vendor/js/ext-theme-classic.js'))
        ->appendFile($this->basePath('js/ext-person.js')); ?>

</head>
<body>
<div class="container">
    <?php echo $this->content; ?>
    <!-- /container -->
    <?php echo $this->inlineScript() ?>
    <hr>
    <footer>
        <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies
            Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
    </footer>
</div>

</body>
</html>
